### ISSUE TITLE
Update "NIST IR" short code for series back to "NISTIR"

### ISSUE THREAD

**Issue by mico** [metanorma/nist-pubid#12]
By looking at the documentation here https://github.com/metanorma/nist-pubid/blob/main/README.adoc you can see there are examples for NISTIR, I believe they are wrong:

> - NIST IR series
>   - NIST IR 8011v3
>   - NIST IR 8204/Upd 1:2019
>   - NIST IR 8115(spa)

In the series list there it's "NISTIR".

First, looking at that, I thought it is mistake and updated "NISTIR" to "NIST IR" in the [`series.yaml`](https://github.com/metanorma/nist-pubid/blob/main/series.yaml)
But after reading relaton-nist specs (https://github.com/relaton/relaton-nist/blob/master/spec/relaton_nist_spec.rb) I realized probably it should be "NISTIR"

**Comment by ronaldtse** [comment]
@mico the latest spec is located here: https://github.com/metanorma/nist-pubid/issues/6

Traditionally (since 1960s), a "NIST Interagency Report" is called a "NISTIR" (no space).

In the NIST PubID scheme (see #6), it is renamed to be "NIST IR" for consistency.

The main use case for Relaton is used to search for a particular reference, so we should support both "NISTIR XXX" and "NIST IR XXX".

In our case, since we are only dealing with NIST PubID, we should use "NIST IR".
<img width="794" alt="Screenshot 2021-12-05 at 2 38 19 PM" src="https://user-images.githubusercontent.com/11865/144736480-559c06ac-9eef-4719-8d69-3d299ca44cf2.png">
<img width="1082" alt="Screenshot 2021-12-05 at 2 38 31 PM" src="https://user-images.githubusercontent.com/11865/144736488-2cfb282a-68cf-4a93-ba45-955bc4e9622c.png">

**Comment by mico** [comment]
@ronaldtse so seems don't need any changes, only update examples (specs) in [relaton/relaton-nist](https://github.com/relaton/relaton-nist) right?

**Comment by ronaldtse** [comment]
Yes, but keep in mind that relaton-nist we will need to still support the search syntax of "NISTIR", but the PubID should always be "NIST IR" (machine readable NIST.IR").
