### ISSUE TITLE
Parsing draft stage

### ISSUE THREAD

**Issue by mico** [metanorma/nist-pubid#15]
There are few ways how to define draft stage:

> NIST SP 2PD 1800-13B
> NIST SP PreD 1800-19B
> NIST SP IPD 800-53r5

(from https://github.com/metanorma/nist-pubid/blob/main/README.adoc)
Where did it come from?

> NIST SP(2PD) 800-188
> NIST SP(IPD) 800-53r5
> NIST SP(PRD) 1800-19B

(from https://www.nist.gov/system/files/documents/2021/08/26/Publication-ID-Proposal_26Aug21.pdf "3.3 PubID Examples")

> SP 800-80(PD)
> SP 800-57pt2r1 (2PD)
> SP 800-205 (February 2019) (PD)

(in https://github.com/relaton/relaton-nist/blob/master/spec/relaton_nist_spec.rb)

I believe in the last one it should be `2PD` not `PD`, but maybe it's also the old way how to write it, is it?

I implemented parsing for the examples from README.adoc, but now it's not working for `relaton-nist` examples and it's very different in the proposal. So, should we support both?

**Comment by ronaldtse** [comment]
> I believe in the last one it should be 2PD not PD, but maybe it's also the old way how to write it, is it?

1. The "2PD", etc. stage codes are **only** used by the NIST CSD and ACD (see NIST PubID, B.2).
2. In a previous version of the NIST PubID scheme, it supported what is called a generic "Public Draft" ("PD") that is meant to be used to describe an FPD (Final Public Draft) with no IPD (Initial Public Draft).
   * i.e. IPD, 2PD, ... FPD requires more than 1 draft. Some documents only have 1 draft in total.
3. I do not believe "PD" was ever used officially since that NIST PubID version was never published publicly.

Let's remove "(PD)" for now until we hit some error.

**Comment by ronaldtse** [comment]
> NIST SP 2PD 1800-13B
> NIST SP PreD 1800-19B
> NIST SP IPD 800-53r5

and

> SP 800-80(PD)
> SP 800-57pt2r1 (2PD)
> SP 800-205 (February 2019) (PD)

These were from the previous version of NIST PubID. Let's only use the new (published) version. "PreD" is now "PRD" (Preliminary Draft) in the latest PubID.

**Comment by mico** [comment]
@ronaldtse should we parse both, `NIST SP 800-57pt2r1 (2PD)` and `NIST SP 2PD 800-57pt2r1`?
and a short version will be: `NIST SP 800-57pt2r1(2PD)` without space, as in NIST PubID?

**Comment by ronaldtse** [comment]
@mico there's no need to, the previous version of NIST PubID was not publicly used, so these IDs should not technically appear.
