### ISSUE TITLE
Outstanding issues with bulk database conversion (2022-01-19)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/nist-pubid#94]
I've generated this report and highlighted all the duplicated values. 

Every duplicated value means that the PubID generation was not unique -- in the original XML, every entry was unique and had a unique DOI. The highlighted cells indicate that the PubIDs have duplicates, and therefore cannot be differentiated with at least one other document.

I used these steps to first highlight and then filter the values:
https://www.extendoffice.com/documents/excel/4081-excel-show-only-duplicate-rows.html

After highlighting:
<img width="919" alt="Screenshot 2022-01-20 at 1 32 28 AM" src="https://user-images.githubusercontent.com/11865/150183644-f154061a-2da9-4347-abbb-7a7360da5731.png">

After filtering the highlights:

<img width="916" alt="Screenshot 2022-01-20 at 9 58 54 AM" src="https://user-images.githubusercontent.com/11865/150248733-9fc38e88-cf9b-4f73-b0bc-2a9f6a2e3f51.png">

Wow: there are only 117 entries that need further fixing here! (both duplications will show up here)

<img width="168" alt="Screenshot 2022-01-20 at 9 59 47 AM" src="https://user-images.githubusercontent.com/11865/150249032-3feea4ae-5d23-491b-bb30-f8e0ad49aeab.png">

We can see there are several patterns that are problematic, e.g.
* A revision without number, e.g. `NISTIR 8115r1`.
* 2 digit year, e.g. `NIST FIPS 54-1-Jan15`
* Missing series, e.g. `NBS CSM {NNN}`
* 1 volume split into two documents, e.g. `NBS SP 535v2a-l`, `NBS SP 535v2m-z`.
* etc.

@mico can you help file separate issues for separate categories (e.g. 1 issue per problematic pattern) for these highlighted entries, and then we can fix them one by one? Thanks.

[nist-pubid-report.xlsx](https://github.com/metanorma/nist-pubid/files/7901716/nist-pubid-report.xlsx)

**Comment by mico** [comment]
NBS CSM 1 - it's not a missing series, parsing error here because we don't have regexp for only one number
NBS CIRC 13e2revJune1908 - need to update revision parsing
NBS CIRC 24supJan1924 - update supplement parsing
NBS CIRC e2 - need to add document number
NBS CIRC supJun1925-Jun1926 and NBS CIRC supJun1925-Jun1927 - should add date range for supplement?
NBS CRPL 1-2_3-1 - should we accept 1-2_3-1 as acceptable document number?
NBS IR 73-197r (NBS SP 389r)- parse as revision 1 ?
NBS MP 275 and NIST MP 275 have link to the same document, so should we just remove NIST MP 275 from report?
NBS RPT ADHOC - add document number?
NBS report ; Apr-Jun1948 - should I parse date as docnumber?
how to parse this? NBS SP 535v2a-l and NBS SP 535v2m-z?
NIST FIPS 54-1-Jan15  two digits year
NIST IR 4743rJun1992 - revision with year and month
NIST AMS 300-8r1 (February 2021 update), NISTIR 8115r1/upd - missing update
NIST GCR 21-917-48v3B - letter in the version number

that's all cases I see here

**Comment by ronaldtse** [comment]
> how to parse this? NBS SP 535v2a-l and NBS SP 535v2m-z?
> NIST GCR 21-917-48v3B - letter in the version number

The `v` here is not for version but for volume. Will make a new issue.

**Comment by ronaldtse** [comment]
@mico are these done? If so we can close this. Thanks!
